### ISSUE TITLE
Image file from ICG dataset does not exist

### ISSUE THREAD

**Issue by ajdillhoff** [poier/PreView#3]
I downloaded and configured the data paths per the README (I hope). The initialization seems to be fine, but running `python main_run.py` fails. Here is the output:

```
(py27) alex@VLM-Dev02:~/dev/examples/PreView/source$ python main_run.py
Init ICG Dataset...
  labeled: read 289 sample(s) from 32 file(s) in 0.773726sec.
  unlabeled: read 63447 sample(s) from 3 file(s) in time: 0.511618
ICG Dataset init done.
Using 63736 samples for training
  289 labeled
  63447 unlabeled
Init ICG Dataset...
  labeled: read 100 sample(s) from 8 file(s) in 0.06394sec.
  unlabeled: read 1487 sample(s) from 1 file(s) in time: 0.020417
ICG Dataset init done.
Using 100 samples for validation
  100 labeled (might be incorrect if a subset is used (e.g., wrt. train set size))
Init ICG Dataset...
  labeled: read 237 sample(s) from 17 file(s) in 0.15207sec.
  unlabeled: read 0 sample(s) from 0 file(s) in time: 2.99999999998e-06
ICG Dataset init done.
Using 237 samples for test
  237 labeled
Traceback (most recent call last):
  File "main_run.py", line 151, in <module>
    model_discriminator=model_d)
  File "/home/alex/dev/examples/PreView/source/trainer/SuperTrainer.py", line 62, in train
    optim_type=args.optim_type)
  File "/home/alex/dev/examples/PreView/source/trainer/ViewPredAndHaPeTrainer.py", line 128, in train
    self.train_epoch(epoch, model, optimizer, out_crop_size)
  File "/home/alex/dev/examples/PreView/source/trainer/ViewPredAndHaPeTrainer.py", line 163, in train_epoch
    in enumerate(self.train_loader):
  File "/home/alex/anaconda3/envs/py27/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/alex/anaconda3/envs/py27/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
UserWarning: Traceback (most recent call last):
  File "/home/alex/anaconda3/envs/py27/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/alex/dev/examples/PreView/source/data/IcgHandPoseDataset.py", line 133, in __getitem__
    min_ratio_inside=self.args_data.min_ratio_inside)
  File "/home/alex/dev/examples/PreView/source/data/IcgHandPoseDataset.py", line 506, in load_sample_icg
    (Filename: {})".format(filepath))
UserWarning: Image file from ICG dataset does not exist             (Filename: /home/alex/dev/datasets/mvhands/Gener8_20161003/Actor03/Test/Free/Cam_0005-1207-0034-1221/DepthImagesDistorted/frame000585.png)
```

Sure enough, the file does not exist. I checked the path of `mvhands/Gener8_20161003/Actor3/` and the only folders in there are `Left` and `Right`. I downloaded the dataset today. 

Did I overlook a step?

**Comment by poier** [comment]
Hi,
obviously, I missed some folders when assembling the dataset for publication. Sorry for that!
I just added the missing files and will upload the updated dataset. This will take some time, though.

**Comment by ajdillhoff** [comment]
No worries. Thanks for the update. Will you comment here when the upload is complete?

**Comment by poier** [comment]
The upload completed.
(The dataset file is even smaller now, since I found that (large) redundant files were included)
